name: iOS Build (manual)

on:
  workflow_dispatch:
  push:
    tags:
      - "ios-build/*"

concurrency:
  group: ios-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ios-build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      # 署名はローカルMac運用を前提（必要に応じて将来拡張）
      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign
